# Generated by Django 4.1.3 on 2022-11-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_files"),
    ]

    operations = [
        migrations.RenameField(model_name="files", old_name="pdf", new_name="data",),
    ]
