# Generated by Django 4.1.3 on 2022-11-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_rename_pdf_files_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="files",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="files/covers/"),
        ),
        migrations.AlterField(
            model_name="files",
            name="data",
            field=models.FileField(upload_to="files/data/"),
        ),
    ]
