# Generated by Django 4.1.3 on 2022-12-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_files_cover_alter_files_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="files",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="files", name="data", field=models.FileField(upload_to=""),
        ),
    ]
